// The Lua engines, carried inside the binary. Generated by cmake/EmbedLua.cmake.
#pragma once

#include <cstddef>
#include <vector>

namespace nt::embedded
{
struct File
{
    const char* name;    // relative to Engines/, e.g. "good-idea/gi_idea.lua"
    const char* data;
    std::size_t size;
};

const std::vector<File>& files();
} // namespace nt::embedded
