# Writes every .lua under ROOT into OUT as a C++ table of byte arrays, so the
# app carries its engines inside itself. Run by the build; see CMakeLists.txt.

file(GLOB_RECURSE files RELATIVE ${ROOT} ${ROOT}/*.lua)
list(SORT files)

set(body "// Generated by cmake/EmbedLua.cmake - do not edit.\n#include \"EmbeddedLua.h\"\n\nnamespace nt::embedded\n{\n")
set(table "")
set(index 0)
foreach(f ${files})
    file(READ ${ROOT}/${f} hex HEX)
    string(LENGTH "${hex}" hexlen)
    math(EXPR size "${hexlen} / 2")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    string(APPEND body "static const unsigned char file${index}[] = { ${bytes} 0 };\n")
    string(APPEND table "    { \"${f}\", reinterpret_cast<const char*> (file${index}), ${size} },\n")
    math(EXPR index "${index} + 1")
endforeach()
string(APPEND body "\nconst std::vector<File>& files()\n{\n    static const std::vector<File> list {\n${table}    };\n    return list;\n}\n\n} // namespace nt::embedded\n")
file(WRITE ${OUT} "${body}")
